<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-04-03T13:30:13 IST" name="Default suite" finished-at="2023-04-03T13:31:14 IST" duration-ms="61323">
    <groups>
    </groups>
    <test started-at="2023-04-03T13:30:13 IST" name="Default test" finished-at="2023-04-03T13:31:14 IST" duration-ms="61323">
      <class name="testcases.TestMethods">
        <test-method is-config="true" signature="beforetest()[pri:0, instance:testcases.TestMethods@4218d6a3]" started-at="2023-04-03T13:30:13 IST" name="beforetest" finished-at="2023-04-03T13:30:54 IST" duration-ms="41284" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforetest -->
        <test-method signature="SearchOperation()[pri:0, instance:testcases.TestMethods@4218d6a3]" started-at="2023-04-03T13:30:55 IST" name="SearchOperation" finished-at="2023-04-03T13:31:07 IST" duration-ms="12198" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SearchOperation -->
        <test-method signature="Verify_Access_Fb()[pri:1, instance:testcases.TestMethods@4218d6a3]" started-at="2023-04-03T13:31:07 IST" name="Verify_Access_Fb" finished-at="2023-04-03T13:31:11 IST" duration-ms="3990" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verify_Access_Fb -->
        <test-method signature="VarifyLogin()[pri:2, instance:testcases.TestMethods@4218d6a3]" started-at="2023-04-03T13:31:11 IST" name="VarifyLogin" finished-at="2023-04-03T13:31:14 IST" duration-ms="2360" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Facebook – log in or sign up] but found [Log in to Facebook]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Facebook – log in or sign up] but found [Log in to Facebook]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at objects.FbPage.VarifyLogin(FbPage.java:32)
at testcases.TestMethods.VarifyLogin(TestMethods.java:48)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VarifyLogin -->
        <test-method is-config="true" signature="aftertest()[pri:0, instance:testcases.TestMethods@4218d6a3]" started-at="2023-04-03T13:31:14 IST" name="aftertest" finished-at="2023-04-03T13:31:14 IST" duration-ms="822" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftertest -->
      </class> <!-- testcases.TestMethods -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
